name: Publish Windows Forms App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore dependencies
        run: dotnet restore AssetPackWorkspaces/AssetPackWorkspaces.csproj

      - name: Build
        run: dotnet build AssetPackCreator.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish AssetPackCreator.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp
